backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: "https://muncangkopong.desa.id"
display_url: "https://muncangkopong.desa.id"
logo_url: "/logo-kkm.png"

locale: "id"

collections:
  - name: "berita"
    label: "Berita Desa"
    folder: "src/content/berita"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul Berita", name: "title", widget: "string" }
      - {
          label: "Tanggal Publish",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          date_format: "DD/MM/YYYY",
          time_format: false,
        }
      - {
          label: "Penulis",
          name: "author",
          widget: "string",
          default: "Admin Desa",
        }
      - {
          label: "Deskripsi Singkat (Untuk Pratinjau/WhatsApp)",
          name: "description",
          widget: "text",
        }
      - {
          label: "Foto Utama Berita",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Isi Berita Lengkap", name: "body", widget: "markdown" }
